# Supabase values.yaml configuration that uses Kubernetes secrets

secret:
  # JWT configuration (used by Studio, Storage, Kong, Analytics, Auth, Rest, Realtime)
  jwt:
    # Leave these blank as they will be loaded from the secret
    anonKey: ""
    serviceKey: ""
    secret: ""
    # Reference to the Kubernetes secret containing JWT values
    secretRef: "supabase-secrets"
    # Keys in the secret that contain the values
    secretRefKey:
      anonKey: jwt.anonKey
      serviceKey: jwt.serviceKey
      secret: jwt.secret

  # Database credentials (required even when using external database)
  db:
    username: ""
    password: ""
    database: ""
    # Reference to the Kubernetes secret containing database credentials
    secretRef: "supabase-secrets"
    # Keys in the secret that contain the values
    secretRefKey:
      username: db.username
      password: db.password
      database: db.database

  # Analytics Logflare API key
  analytics:
    apiKey: ""
    # Reference to the Kubernetes secret containing analytics API key
    secretRef: "supabase-secrets"
    # Key in the secret that contains the value
    secretRefKey:
      apiKey: analytics.apiKey

  # SMTP configuration for authentication emails
  smtp:
    # Leave these blank as they will be loaded from the secret
    username: ""
    password: ""
    # Reference to the Kubernetes secret containing SMTP credentials
    secretRef: "supabase-secrets"
    # Keys in the secret that contain the values
    secretRefKey:
      username: smtp.username
      password: smtp.password

  # Secret used to access the studio dashboard (leave empty to disable authentication)
  dashboard:
    # Leave these blank as they will be loaded from the secret
    username: ""
    password: ""
    # Reference to the Kubernetes secret containing dashboard credentials
    secretRef: "supabase-secrets"
    # Keys in the secret that contain the values
    secretRefKey:
      username: dashboard.username
      password: dashboard.password

  # S3 credentials for storage
  s3:
    # Leave these blank as they will be loaded from the secret
    keyId: ""
    accessKey: ""
    # Reference to the Kubernetes secret containing S3 credentials
    secretRef: "supabase-secrets"
    # Keys in the secret that contain the values
    secretRefKey:
      keyId: s3.keyId
      accessKey: s3.accessKey

# Storage configuration - if using AWS S3
storage:
  environment:
    # Enable S3 storage backend
    STORAGE_BACKEND: s3
    # Use the bucket name from your configuration
    GLOBAL_S3_BUCKET: "webtree-makelocal-supabase"
    # Set the AWS region
    AWS_DEFAULT_REGION: "eu-central-1"

# SMTP configuration for Auth service
auth:
  environment:
    # These values will be replaced with values from the secret at runtime
    GOTRUE_SMTP_ADMIN_EMAIL: "admin@makelocal.net"
    GOTRUE_SMTP_HOST: "email-smtp.eu-central-1.amazonaws.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "makelocal.net"
    # Configure other SMTP settings as needed
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"

# Set your external URL
kong:
  ingress:
    enabled: true
    hosts:
    - host: makelocal.net
      paths:
      - path: /
        pathType: Prefix

studio:
  environment:
    SUPABASE_PUBLIC_URL: "https://makelocal.net"
